name: Manual Playwright Test

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Which project to test'
        required: true
        default: 'KVNL - chromium'
        type: choice
        options:
          - 'KVNL - chromium'
          - 'KVB - chromium'
          - 'TP - chromium'
          - 'All projects'

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run specific project test
        if: github.event.inputs.project != 'All projects'
        run: npx playwright test --project="${{ github.event.inputs.project }}" --reporter=list

      - name: Run all tests
        if: github.event.inputs.project == 'All projects'
        run: npx playwright test --reporter=list

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/